---
application:
  name: "novel-reader"
  project: "reader-novel"
  organization: "QoveryCommunity"
routers:
- name: "main-novel-reader"
  routes:
  - application_name: "novel-reader"
    paths:
    - "/*"
